# Generated by Django 6.0 on 2025-12-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0001_initial'),
        ('registration_and_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_access_code', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('qualified', 'Qualified'), ('disqualified', 'Disqualified')], default='qualified', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_states', to='registration_and_settings.competition')),
            ],
            options={
                'unique_together': {('competition', 'participant_access_code')},
            },
        ),
    ]
