# Generated by Django 6.0 on 2025-12-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0002_competitorstate'),
        ('registration_and_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('generated_questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_and_settings.competition')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
