# Generated by Django 6.0 on 2025-12-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_master', '0003_gametracker'),
        ('registration_and_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_access_code', models.CharField(max_length=10)),
                ('round_number', models.IntegerField()),
                ('selected_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(default=False)),
                ('correct_answer_ref', models.CharField(max_length=100)),
                ('time_taken', models.FloatField(help_text='Time in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_and_settings.competition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_master.biblequestion')),
            ],
        ),
    ]
